services:
  kolase:
    build: .
    container_name: kolase-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_PATH=/app/data/database.sqlite
      - COOKIE_SECURE=true
    volumes:
      - kolase-db:/app/data
      - kolase-uploads:/app/public/uploads

volumes:
  kolase-db:
  kolase-uploads:
